### ISSUE TITLE
GET http://127.0.0.1:8080/undefined net::ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by shreyansh26** [rishz/URL-Shortener#2]
I tested the app with my own firebase credentials and whenever I click on the new link(shortened), it always gives the following error in the console- 
`GET http://127.0.0.1:8080/undefined net::ERR_TOO_MANY_REDIRECTS`
and the URL automatically changes to 127.0.0.1:8080/undefined.

Did you face any such issue, or do you have any solution to it?

**Comment by rishz** [comment]
Hey @shreyansh26 I have resolved this issue and updated the repository.
Thanks!
